---
title: "tutorial_1"
output: html_document
---

Loading some packages 
```{r}
library(network)
library(igraph)
library(reshape2)
library(tidyverse)
```
1.1.1 From adjacency matrix to igraph
```{r}
url1 <- "https://github.com/rensec/sasr08/raw/main/g_adj_matrix_simple.csv"
g_matrix <- read.csv(file = url1, header = FALSE)
g_matrix
class(g_matrix)
g_matrix <- as.matrix(g_matrix)
g_matrix
rownames(g_matrix) <- 1:nrow(g_matrix)
colnames(g_matrix) <- 1:ncol(g_matrix)
g_matrix
# Answer: 5 nodes, 4 edges
g_nodes_age <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_nodes_age.csv")
g_nodes_age
g <- graph_from_adjacency_matrix(g_matrix)
class(g)
g
plot(g)
g <- set_vertex_attr(g, 
                     name = "age",
                     value = g_nodes_age$age)
```
1.1.2
```{r}
g_elist <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_elist.csv")
g_elist
g_from_elist <- graph_from_data_frame(g_elist) 
plot(g_from_elist)
g_from_elist <- graph_from_data_frame(g_elist, vertices = g_nodes_age) 
plot(g_from_elist)

# Assignment:
igraph_from_elist <- graph_from_data_frame(g_elist, vertices = g_nodes_age) %>%
  plot()
```
1.1.3
```{r}
g_adj_list <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_adj_list.csv")
g_adj_list
g_elist_from_alist <- g_adj_list
g_elist_from_alist <-  select(g_elist_from_alist, id, friend1:friend2) # keep only the network variables (and id)
g_elist_from_alist <-  melt(g_elist_from_alist, id.vars = "id") # from the reshape2 package
g_elist_from_alist
g_elist_from_alist <- g_adj_list %>% 
  select(id, friend1:friend2) %>% # keep only the network variables (and id)
  melt( id.vars = "id") # from the reshape2 package
g_adj_list %>% # (we don't save it into an object as above this time, since we just want to show that the result is the same)
  select(id, friend1:friend2) %>% #keep only the network variables (and id)
  pivot_longer(c(friend1, friend2))
g_elist_from_alist <- g_elist_from_alist%>% 
  filter(!is.na(value)) %>% # drop the missings
  rename(from ="id", to = "value", sourcevar= "variable") %>% #just nice for interpretation
  relocate(to, .after=from) #move around the columns
# Answer: To keep track of the meaning of ties. For example, the first friend people list may be the best friend. 
g_elist_from_alist
g_from_alist <- graph_from_data_frame(g_elist_from_alist) #This is a proper igraph graph object
plot(g_from_alist)
nodelist <- select(g_adj_list,id,age)
g_from_alist <- graph_from_data_frame(g_elist_from_alist, vertices = nodelist) #This is a proper igraph graph object
plot(g_from_alist)

# Assignment

g_elist_from_alist <- g_adj_list %>%
  select(id, friend1:friend2) %>%
  melt(id.vars = "id") %>%
  filter(!is.na(value)) %>%
  rename(from ="id", to = "value", sourcevar= "variable") %>% 
  relocate(to, .after=from)

g_from_aalist <- graph_from_data_frame(
  g_elist_from_alist,
  vertices = select(g_adj_list, id, age)
)

plot(g_from_aalist)

```
1.2.1
```{r}
g_adj_matrix <- as_adjacency_matrix(g, sparse = FALSE)
g_adj_matrix
all(g_adj_matrix == g_matrix)
```
1.2.2
```{r}
g_edgelist <- igraph::as_data_frame(g_from_elist, what = "edges") 
g_edgelist 
igraph::as_data_frame(g_from_elist, what = "vertices") 
```
1.2.3
```{r}
edgelist_2 <- igraph::as_data_frame(g_from_alist, what = "edges")
nodelist_2 <- igraph::as_data_frame(g_from_alist, what = "vertices")
# Note the use of the "namespace" "igraph::" here, to indicate that we need the igraph function here, not the function with the same name from the dplyr/tidyverse package

d <- edgelist_2 %>%
  rename(id = "from") %>% 
  pivot_wider( id_cols = id, names_from = sourcevar, values_from = to ) %>% 
  merge(nodelist_2, by.x = "id", by.y = "name", all.y = TRUE ) %>% 
  relocate(age, .after = id) %>% 
  type_convert() #as_data_frame returns characters; this transforms it back to numeric
d
```
1.3
```{r}
g_np <- as.network(g_elist_from_alist, matrix.type = "edgelist", vertices = nodelist)
g_np
plot(g_np)
```
1.4
```{r}
g_mod <- delete_vertices(g,2)
plot(g_mod)
g_mod <- delete_vertices(g,which(V(g)$age == 21))
plot(g_mod)

# Assignment
g_mod <- delete.vertices(g,which(is.na(V(g)$age)))
plot(g_mod)

V(g)$gender <- c("male", "female", "female", "other", "male") 
g
g_rev <- reverse_edges(g)
plot(g_rev)
g_union <- igraph::union(g, g_rev)
# Answer: All arrows will be two-sided?
plot(g_union)
g_undir <- as_undirected(g)
plot(g_undir)
# Answer: One is undirected and one is directed in both directions.
```

2
```{r}
library(igraph)
z <- make_graph("Zachary")
z
plot(z)
is_directed(z)
```
2.1.1
```{r}
vcount(z)
ecount(z)
```
2.1.2
```{r}
edge_density(z)
z$density <- edge_density(z)
z
```
2.1.3
```{r}
count_components(z)
```
2.1.4
```{r}
diameter(z)
mean_distance(z)
```
2.1.5
```{r}
transitivity(z, type="average")
```
2.2.1
```{r}
degree(z)
summary(degree(z))
hist(degree(z))
V(z)$degree <- degree(z)
#We add  + 8 to degree to avoid that the lowest-degree nodes become really small and specify margin = -0.1 to reduce the whitespace around the plot
plot(z, vertex.size = V(z)$degree+8, margin= -0.1)
degree(z, v = 3)
```
2.2.2
```{r}
betweenness(z)
z <- z %>% 
  set_vertex_attr(
    name = "betweenness",
    value = betweenness(z)
  )
```
2.2.3
```{r}
V(z)$closeness <- closeness(z)
```

3
```{r}
library(igraph)
library(haven) # to read Stata files
library(reshape2)
library(tidyverse)
```
3.1
```{r}
PupilsWaveV <- read_dta(file = "PupilsWaveV.dta")
head(PupilsWaveV)
tail(PupilsWaveV)
class12b <- PupilsWaveV %>% 
  filter(schoolnr == "12b")  # keep only one class
```
3.2
```{r}
# 1 Adjacency list to igraph 
p_elist_from_alist <- class12b %>%
  select(namenr, friend1:friend12) %>%
  melt(id.vars = "namenr") %>%
  filter(!is.na(value)) %>%
  rename(from ="namenr", to = "value", sourcevar= "variable") %>% 
  relocate(to, .after=from)
p_aalist <- graph_from_data_frame(p_elist_from_alist, vertices = select(class12b,namenr,age,sex))
p <- p_aalist
# 2 Checking if directed
is_directed(p)
# 3 Visualize
plot(p)
# 4 Five number summary
vcount(p)
ecount(p)
edge_density(p)
count_components(p)
diameter(p)
mean_distance(p)
transitivity(p, type = "average")
# 5 Test hypothesis that girls have higher degree than boys
deg <- degree(p)
df_deg <- data.frame(
  sex    = V(p)$sex,
  degree = deg
)
t.test(degree~sex, data = df_deg, alternative = "greater")
# 6
#We add  + 8 to degree to avoid that the lowest-degree nodes become really small and specify margin = -0.1 to reduce the whitespace around the plot
V(p)$degree <- degree(p)
plot(p, vertex.size = V(p)$degree+8, vertex.color = V(p)$sex, margin= -0.1)
```

4
```{r}
library(spdep) #We need the spdep package for the spatial weight matrix and for the Moran's I test
library(spatialreg) #We need the spatialreg package for the spatial lag and spatial error models
```
4.1
